// lab-module05-metaframeworks/nuxt/app/pages/houses/index.vue
<!-- app/pages/houses/houses.vue -->
<script setup lang="ts">
import Filters from '~/components/house-list/Filters.vue';
import HouseList from '~/components/house-list/HouseList.vue';
import { useHouseApi } from '~/composables/useHouseApi';

const config = useRuntimeConfig();
const route = useRoute();

const { getHouseList } = useHouseApi()

const houses = await getHouseList();

const search = computed(() => {
  const value = route.query.search;

  return typeof value === 'string' ? value.toLowerCase() : '';
});

const filteredHouseList = computed(() => {
  if (!search.value) {
    return houses;
  }

  return houses.filter((house) => {
    return (
      house.name.toLowerCase().includes(search.value) ||
      house.city.toLowerCase().includes(search.value) ||
      house.country.toLowerCase().includes(search.value) ||
      house.address.toLowerCase().includes(search.value)
    );
  });
});

useSeoMeta({
  title: `${config.public.siteName} · Refugios Rurales`,
});


</script>

<template>
   <div class="flex flex-col gap-12">
      <section class="flex flex-col gap-5">
        <div class="flex flex-col items-center justify-center gap-2 text-center">
          <h2 class="text-2xl font-display font-bold text-primary sm:text-3xl">
            Encuentra tu refugio en la naturaleza
          </h2>
          <p class="max-w-2xl text-sm leading-relaxed sm:text-base">
            Descubre casas rurales únicas, diseñadas para desconectar y
            reconectar con lo esencial.
          </p>
        </div>

        <Filters />
      </section>

      <section class="flex flex-col gap-5">
        <h3 class="text-xl font-display font-bold text-primary sm:text-2xl">
          Nuestras recomendaciones
        </h3>
        <HouseList :house-list="filteredHouseList" />
      </section>
    </div>
</template>

<style scoped>

</style>

// lab-module05-metaframeworks/tanstack-start/src/routes/houses/index.tsx
import { createFileRoute } from '@tanstack/react-router';
import { api, HouseList, mapHouseListFromApiToVm } from '#pods/house-list';
import { Filters } from '#pods/house-list/filters.component.js';

export const Route = createFileRoute('/houses/')({
  head: () => ({
    meta: [{ title: 'Rurall - Refugios Rurales' }],
  }),
  validateSearch: (search: { search?: string }) => ({
    search: search.search ?? '',
  }),
  loader: () => api.getHouseList(),
  staleTime: 10_000,
  component: RouteComponent,
});

function RouteComponent() {
  const { search } = Route.useSearch();
  const houses = Route.useLoaderData();

  const filteredHouseList = houses.filter((house) => {
    if (!search) return true;

    const query = search.toLowerCase();

    return (
      house.name.toLowerCase().includes(query) ||
      house.city.toLowerCase().includes(query) ||
      house.country.toLowerCase().includes(query) ||
      house.address.toLowerCase().includes(query)
    );
  });

  return (
    <div className="flex flex-col gap-12">
      <section className="flex flex-col gap-5">
        <div className="flex flex-col items-center justify-center gap-2 text-center">
          <h2 className="text-2xl font-display font-bold text-primary sm:text-3xl">
            Encuentra tu refugio en la naturaleza
          </h2>
          <p className="max-w-2xl text-sm leading-relaxed sm:text-base">
            Descubre casas rurales únicas, diseñadas para desconectar y
            reconectar con lo esencial.
          </p>
        </div>

        <Filters />
      </section>

      <section className="flex flex-col gap-5">
        <h3 className="text-xl font-display font-bold text-primary sm:text-2xl">
          Nuestras recomendaciones
        </h3>
        <HouseList houseList={mapHouseListFromApiToVm(filteredHouseList)} />
      </section>
    </div>
  );
}
