// lab-module05-metaframeworks/tanstack-start/src/components/hero.component.tsx
import { Link } from '@tanstack/react-router';

export const Hero = () => {
  return (
    <section className="relative flex min-h-[calc(100vh-8rem)] flex-col items-center justify-center overflow-hidden rounded-2xl bg-[url(/javier-rincon-lSwy-mj3h4M-unsplash.jpg)] bg-cover bg-center px-6 py-12 text-center sm:min-h-[calc(100vh-10rem)] lg:px-12">
      <div className="absolute inset-0 bg-black/35" />
      <div className="relative z-10 flex max-w-2xl flex-col items-center justify-center gap-5 text-secondary">
        <h2 className="font-display text-4xl leading-tight md:text-5xl lg:text-6xl">
          Tu refugio rural te espera
        </h2>
        <p className="max-w-xl text-sm leading-relaxed sm:text-base md:text-lg">
          Desconecta de la rutina y reconecta con la naturaleza en nuestros
          alojamientos cuidadosamente seleccionados.
        </p>

        <div className="rounded-2xl bg-tertiary transition hover:bg-tertiary/70">
          <Link
            to="/houses"
            className="block px-6 py-3 font-medium text-secondary"
          >
            Explorar casas
          </Link>
        </div>
      </div>
    </section>
  );
};

// lab-module05-metaframeworks/nuxt/app/components/Hero.vue
<!-- app/components/AppFooter.vue -->
<template>
  <section class="relative flex min-h-[calc(100vh-8rem)] flex-col items-center justify-center overflow-hidden rounded-2xl bg-[url(/javier-rincon-lSwy-mj3h4M-unsplash.jpg)] bg-cover bg-center px-6 py-12 text-center sm:min-h-[calc(100vh-10rem)] lg:px-12">
      <div class="absolute inset-0 bg-black/35" />
      <div class="relative z-10 flex max-w-2xl flex-col items-center justify-center gap-5 text-secondary">
        <h2 class="font-display text-4xl leading-tight md:text-5xl lg:text-6xl">
          Tu refugio rural te espera
        </h2>
        <p class="max-w-xl text-sm leading-relaxed sm:text-base md:text-lg">
          Desconecta de la rutina y reconecta con la naturaleza en nuestros
          alojamientos cuidadosamente seleccionados.
        </p>

        <div class="rounded-2xl bg-tertiary transition hover:bg-tertiary/70">
          <NuxtLink
            to="/houses"
            class="block px-6 py-3 font-medium text-secondary"
          >
            Explorar casas
          </NuxtLink>
        </div>
      </div>
    </section>
</template>

<style scoped>

</style>
