// lab-module05-metaframeworks/nuxt/app/components/house-detail/DetailImage.vue
<script setup lang="ts">
import type { House } from '~/types/house';

const props = defineProps<{
    house: House
}>()
</script>

<template>
    <div class="relative aspect-16/8 w-full overflow-hidden rounded-2xl sm:aspect-16/7 lg:aspect-16/6">
      <img
        :src="house.image"
        :alt="house.name"
        sizes="(max-width: 640px) 100vw, 100vw"
        class="h-full w-full object-cover"
      />
    </div>
</template>

<style scoped>

</style>

// lab-module05-metaframeworks/tanstack-start/src/pods/house/components/detail-image.component.tsx
import * as viewModel from '../house.vm';

interface Props {
  house: viewModel.House;
}

export const DetailImage: React.FC<Props> = (props) => {
  const { house } = props;
  return (
    <div className="relative aspect-16/8 w-full overflow-hidden rounded-2xl sm:aspect-16/7 lg:aspect-16/6">
      <img
        src={house.image}
        alt={house.name}
        sizes="(max-width: 640px) 100vw, 100vw"
        className="object-cover"
      />
    </div>
  );
};
